inherit_from:
  - .rubocop-airbnb.yml

# Rails用に最適化
Rails:
  Enabled: true

# 文字数の上限を80文字から130文字に変更
Layout/LineLength:
  Max: 130

# rubocopで検証したくないフォルダを指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'